# Generated by Django 5.1.5 on 2025-02-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
