# Generated by Django 5.1.5 on 2025-02-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='description',
            field=models.CharField(default='No description available', max_length=2000),
            preserve_default=False,
        ),
    ]
